services:
  memgraph:
    image: memgraph/memgraph:3.1.1
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    command: >
      --log-level=TRACE
      --also-log-to-stderr
    restart: unless-stopped

  memgraph-lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - memgraph
    restart: unless-stopped
